#!/bin/sh

if [ -z "$3" ]; then
    echo "Usage: $0 <source dir> <every-nth-frame like 250> <every-milisecond like 20>"
    exit
fi

src="$1"; shift
nth="$1"; shift
sec="$1"; shift

find $src -type f | sort -n | awk "NR % $nth == 0 || NR == 1 { print \$0 }" | xargs -L 1 -d '\n' ./transform
echo -e "\nAnimating."
./animate plots $sec
